export const type = {
  INCREMENT:'INCREMENT',
  ADDCOUNT2:'ADDCOUNT2',
  DECREMENT:'DECREMENT',
  ADDTODO:'ADDTODO',
  CHECKOUT_REQUEST:'CHECKOUT_SUCCESS',
  CHECKOUT_SUCCESS:'CHECKOUT_SUCCESS',
  CHECHOUT_FAILURE:'CHECHOUT_FAILURE',
}